### ISSUE TITLE
Shortcut to set apiName option — possibly rename that option

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/fusspot#25]
I want to start trying to use this library frequently to check function arguments that are not necessary objects. In order to get nice clear error message, then, I need to set that `apiName` option. I was thinking it might be more ergonomic if we could say "If the second argument to `assert` is a string, we'll consider it the equivalent of `apiName`." — e.g. `v.assert(x, 'something')`.

I'm also wondering if we might want to rename the `apiName` option property. I don't really understand the `api` part of that. How about `description`?

@kepta  what do you think?

**Comment by kepta** [comment]
> I'm also wondering if we might want to rename the apiName option property. I don't really understand the api part of that. How about description?

Thats a more logical name, I would recommend deprecating `apiName` and using `description`, to avoid breaking change.

>  if we could say "If the second argument to assert is a string, we'll consider it the equivalent of apiName." — e.g. v.assert(x, 'something').

I am not sure I fully understand what you are suggesting here. (Maybe it has been a while since I used fusspot)

**Comment by davidtheclark** [comment]
I want to be able to get an error message like `accountId should be a string`, instead of `value should be a string`. Right now, I can get close to that with `v.assert(v.string, { apiName: 'accountId' })`, which should give me `accountId: value should be a string`.

I'd like to change things so that I can make a more concise assertion and get a more concise error: `v.assert(v.string, 'accountId')` could give me `accountId should be a string`.
