### ISSUE TITLE
v.number should reject NaN

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/fusspot#29]
Although `typeof NaN === 'number'`, I'd expect that you always want to reject `NaN` if you're expecting a real number.

**Comment by kepta** [comment]
> I'd expect that you always want to reject NaN if you're expecting a real number.

I don't think we should bifurcate fusspots behaviour from standard Javascript. If `NaN` is a number, `fusspot` should treat it as a number, along with other non standard numbers like (Infinity, -Infinity). How about creating something like `v.finite`? Along the lines of [Number.isFinite](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite).

**Comment by davidtheclark** [comment]
I don't know ... I don't know of any situation in which I'd want to *accept* `NaN` in a place where I'm validating for numbers. I guess we could make a different primitive validator — and I'd just always use that one, never use `v.number`.

**Comment by kepta** [comment]
>  I guess we could make a different primitive validator — and I'd just always use that one, never use v.number.

Seems reasonable to me. We already have a v.nonEmptyString dealing similar case for strings. Let us add a `v.finite` validator, which works similar to `Number.isFinite`.

**Comment by t3h2mas** [comment]
Opened #44 to address this

@kepta @davidtheclark
