### ISSUE TITLE
Add Date object validator

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/fusspot#30]
I think every single time I use this project I also want a `Date` object validator.

Here's a quick implementation:

```js
function validateDate(value) {
  if (!(value instanceof Date) || value.toString() === 'Invalid Date') {
    return 'date';
  }
};
```

@kepta any objections to getting this into the main library?

**Comment by kepta** [comment]
No objections. While reading your snippet I wonder if we should also add an `instanceOf` check similar to `PropTypes.instanceOf(..)`. I think this should help asserting if the object is an instance of a given class.
